name: Bug
description: Track bugs and defects related to the project.
title: "[BUG]: "
labels: ["bug", "triage"]
body:
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Low (Annoyance)
        - Medium (Minor functionality broken)
        - High (Core feature/functionality broken)
    validations:
      required: true
  - type: dropdown
    id: size
    attributes:
      label: Size
      options:
        - Small (5 - 30 mins)
        - Medium (30 - 60 mins)
        - Large (60+ mins)
    validations:
      required: true
  - type: dropdown
    id: targetCompletion
    attributes:
      label: Target Completion Date
      options:
        - None
        - Meet 1
        - Meet 2
        - Meet 3
        - Qualifier
        - State
        - Worlds
        - Premere Event
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. When I do '...'
        2. The robot does '...'
        3. The expected behavior is '...'
    validations:
      required: false
  